### ISSUE TITLE
www application in linux 'saves' as zero byte file

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#1]
I have limited programming experience
I have successfully downloaded www for linux
It appears to have installed correctly
I have altered some settings in the default editor tab, they have saved okay.
I have also entered a Graham Wheeler recipe for Marstons Pedigree
To this point everything appears to be running fine
Print to browser seems okay too.

I don't think save is working properly, a zero byte file is created by save.
Once a save has been executed the program will no longer close properly.
I can only get a close by brute force [control/alt/escape in Linux].

[Changing default 'save on close' to 'false' allows the program to close as it should.] 

However if www is opened it will close again successfully if no saves are made.

I might try deleting all files in the www config folder and see if there is any improvement.
This did not provide any improvement.

**Comment by jimbob88** [comment]
Sorry, but may I ask some questions for how you set this up.
Firstly how did you install ( the generic executables or .deb ) - if the former I will most likely need to make a new release for the latest commit. 

If you have installed it from a `.deb` file, please run the command `sudo wheelers-wort-works --coreupdate` to allow the latest downloads yo be installed. 


If your issue still occurs please try running www from terminal with the command `wheelers-wort-works` this will display any errors that have occurred in the process, on finding these errors would it be possible to copy these errors to a [pastebin](https://pastebin.com/) and reply to this message with how you are getting along. 
Thanks, Jim.

**Comment by Bobbicat** [comment]
I installed from the latest .deb [wheelers-wort-works_2.3_all.deb]
I'll follow your instructions and post the results.
received the following after running 'sudo wheelers-wort-works --coreupdate':

`Updating beer_engine.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine.py
Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works/main.py", line 39, in <module>
    update()
  File "<string>", line 12, in update
  File "/usr/include/wheelers-wort-works/main.py", line 24, in resource_path
    if os.path.basename(relative_path) == u'logo.png':
NameError: name 'os' is not defined
`

I will post back after trying www again.

**Comment by Bobbicat** [comment]
Sorry I pressed the close issue button by mistake

www is still saving as a zero byte file
the application will close as I have 'save on close' set on 'false'

I will post again after I have followed your instructions.

**Comment by Bobbicat** [comment]
After pressing 'save file' this error was thrown up:
https://pastebin.com/fLd6xB7D

I'm not signed in to pastebin, maybe I need to create an account?

Thanks, by the way, for your work on this very promising application.

**Comment by jimbob88** [comment]
@Bobbicat Okay, I am in Germany at the moment, I get back Tuesday, I can fix this issue when I return home, Thanks for your bug report

**Comment by jimbob88** [comment]
@Bobbicat May I ask which version you installed and could you run the output of the command:
`cat /usr/include/wheelers-wort-works/update.py`
This may help in a temporary fix.

**Comment by jimbob88** [comment]
@Bobbicat just updated the core branch could you run the update command again - Jim

**Comment by Bobbicat** [comment]
I downloaded wheelers-wort-works_2.3_all.deb from Wheelers-Wort-Works Secondary Stable
...and installed from my downloads folder.

I got this output from the cat command:
https://pastebin.com/HU8AuwxA

I'll run update again and post any results

**Comment by Bobbicat** [comment]
The update threw up no errors

I ran wheelers-wort-works in the console and got:
https://pastebin.com/5KTEU0yp

Save file is still saving zero byte files. They are named, with .berf after the name and appear in ~/.config/Wheelers-Wort-Works/

**Comment by Bobbicat** [comment]
I ran coreupdate again and attempted to creat a file without closing down, an error was announced in the console when I tried to save my file, slightly different from the previous file error:
https://pastebin.com/v1aN7qKf
I'm still getting a zero byte save file.

**Comment by jimbob88** [comment]
When I get back home I'll work on making a fix

**Comment by Bobbicat** [comment]
That's cool. I'll happily continue to test and try. When are you likely to be back?

**Comment by jimbob88** [comment]
@Bobbicat later today (around 5 o'clock GMT)

**Comment by Bobbicat** [comment]
I'll keep checking back, I realise you probably have other stuff to do, as well

**Comment by jimbob88** [comment]
I seemed to have fixed this Issue in the latest `.deb` file, would it be possible for you to test it at some point in time (requires `.deb` update due to the changes in the `main.py` file)

**Comment by Bobbicat** [comment]
I downloaded - wheelers-wort-works_2.4_all.deb
and installed over version 2.3 using qapt-deb-installer.

The program [2.4] now starts up and shuts down with no errors.
I entered data for a brew and saved it successfully. 
I was able to read the .berf file with a text editor.
I restarted wheelers-wort-works and was able to open the file I had just saved.
If I select print to browser I get a copy in my browser and in the program config as an HTML file.

So where I was initially unable to save files, that bug now appears to be fixed.
Congratulations Jim and many thanks. 
I'm sure Graham just raised a glass to you in that beer tent in the sky and there is a big grin across his face.

Bob

* if there is any further testing you need to run just ask
 apart from that I think this bug can be closed as solved

**Comment by Bobbicat** [comment]
If I add a yeast in 'Experimental Attenuation' everything still seems okay.
However if I add 'Irish Moss' errors begin to appear again.

Incidentally it would be nice to have a display of IBU/GU in the calculation area.

**Comment by jimbob88** [comment]
Thank you for your help with Bug Testing, sorry to ask this but would it be possible for you to create a new issue with the error found when adding Irish Moss. 
Thank you very much, for your help in improving wheelers-wort-works 
- Jim
