### ISSUE TITLE
editing grists

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#10]
You create a new grist, or for some reason rename an old one, after having maybe edited it.
Now you use this grist in a recipe, save the recipe and forget all about it.
If you, at some later stage, delete this grist then the files in which it was present will no longer be able to open.
WWW will crash on trying to open said files.

**Comment by jimbob88** [comment]
If you haven't/do not wish to save to your database, yet wish to save the file please on the save dialog type `.berfx` not `.berf` these files carry your current data and so can be opened by any WWW user or by yourself at a later date.
**Quick warning:** these files are larger, not very optimized at this moment in time ( they may take a second to save ), also they overwrite your current variables so pressing save to database after using this file will overwrite your current database.

**Comment by Bobbicat** [comment]
Aah, excellent info. Just what I needed to discover. Thanks, Jim.
I'll give you a little peace now, its time to get a meal ready.  
I suppose a manual will eventually be available to cover this sort of information.

**Comment by jimbob88** [comment]
Yeah, I do need to work on a guide for the correct usage of WWW, I may begin working on this soon.

**Comment by Bobbicat** [comment]
I came across a mountain of stuff written by Graham himself on JBK forums, it has given me quite a few useful hints on setting up and using the software. I'm pleased that you are sticking to his format. 
It is helping me make sense of his recipes, something other software has been unable to do. I found WWW by searching for his original Beer Engine. It is great that someone is making this available across platorms.

**Comment by jimbob88** [comment]
Sounds good, quick note I have a new release available for `.deb` it requires a .deb install as it moves to a new folder system (specific folders for recipes and html).

**Comment by Bobbicat** [comment]
Will 2.4-2 install over 2.4-1 or does the old deb need to be purged first?
I'll try installing over.

**Comment by jimbob88** [comment]
It will install over
