### ISSUE TITLE
.berfx files not saving properly

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#11]
If I open a .berf file in WWW then 'save as' a .berfx version it looks like the data saves over itself producing one with a doubled set of components. 
No error shows in the console.

**Comment by Bobbicat** [comment]
On repeating this, it seems .berfx files are not being opened correctly. Previously properly functioning .berfx files no longer open properly.

**Comment by jimbob88** [comment]
I am sorry but don't feel like I understand the issue, I tested opening `1920s Bitter.berf` (A Graham Wheeler Example) and saved as a `.berfx` with the result being the following two files: [1920s Bitter.berf](https://pastebin.com/f33YDn5W) and [1920s Bitter.berfx](https://pastebin.com/KQ5Kq8np). I see no issues with these files.

**Comment by Bobbicat** [comment]
In WWW I make a new 'No Name' file with grist of 1kg Maris Otter, Hops 4g Admiral.
I save 'No Name' as 'No Name.berf'
I open 'No Name.berf', in the /.config/recipes file, in a text editor and file looks ok.

I restart WWW and open 'No Name.berf' all looks ok in WWW.
I save 'No Name.berf' as 'No Name.berfx'
I open 'No Name.berfx', in the /.config/recipes file, in a text editor and file looks ok.
I close [quit] WWW I get option OK or cancel. I chose OK. 
The program closes with no option to save.
[however in defaults save_close=True]
Again, I open 'No Name.berfx', in the /.config/recipes file, in a text editor.
Now 'No Name.berfx' has the grist component duplicated, similarly the hop component is duplicated.
When I open in WWW There are now two identical Maris Otter rows and two identical Admiral rows.
and calculations show as if these components were doubled.

**Comment by Bobbicat** [comment]
If I open a .berfx file and then save it. On reopening the file a second set of date appears below the first.
so first time I get two rows of Maris Otter repeat the open save ant next time that becomes for rows of Maris Otter and so on.

**Comment by Bobbicat** [comment]
Perhaps this is some glitch because I installed WWW 2.4.2 over 2.4.1. ?
Maybe purge and delete all and do a complete clean re-install?

**Comment by Bobbicat** [comment]
I downloaded the 1920s recipe. This installation is definitely chewing up .berfx files.
I'll search, purge and delete and go for a clean install and see how it turns out.

**Comment by jimbob88** [comment]
This issue doesn't seem to occur on my install ( clean 2.4.2 ) + `sudo wheelers-wort-works --update`. I followed your exact instructions and ended up with the correct options. Perhaps a reinstall is required?

**Comment by Bobbicat** [comment]
I re-installed WWW and am still getting the same result.

**Comment by Bobbicat** [comment]
I think when a save occurs with a .berfx file then the file contents are not replaced the save causes a copy to be added to the already existing file.

**Comment by Bobbicat** [comment]
try running a save repeatedly. Each repeat save adds previous content to what is already there.
Try the same with a .berf file and if no changes are performed, the  file is saved unchanged as it should be.
I will try to explain more if you cannot follow what I have experienced.
I did a deep search of my computer for 'wheeler' files and deleted all related content.
I repeated the search to make sure everything was purged.
I even removed the install .deb file.
I then downloaded a fresh copy of the deb file and installed from that. All previous content including user content was removed. I ran --update.
I added 1000g of Maris Otter and 4g Admiral to 'No Name' saved 'No Name.berf' to recipes.
This file saved, opened, re-saved and re-opened with no problems.
I closed WWW re-opened and checked No Name.berf again, still no problems.
Next I saved 'No Name' as a .berfx file, this is where things began to go astray.
I will explain more in the next post.

**Comment by jimbob88** [comment]
I was able to replicate your issue in Kubuntu simply by opening a `.berfx` then saving it, than reopening it. It seems to be more of an issue opening the file than actually saving it.

**Comment by Bobbicat** [comment]
Perhaps, but I watched by opening the file in a text editor and observing the change take place.

**Comment by jimbob88** [comment]
In respect to your "issue" with no save prompt opening, the code decides to automatically save if it knows there is a file open. As a second thought this isn't a very good idea perhaps some form of prompt should be opened?

**Comment by Bobbicat** [comment]
On first save everything looked fine. On closing WWW when a second save on close occurred I think, the file altered.

**Comment by jimbob88** [comment]
I seemed to have fixed the issue on Ubuntu 18.04 and Kubuntu 18.10 (fix will be pushed within the next few minutes)

**Comment by Bobbicat** [comment]
I found out how to reproduce the problem. 
Load the file. Save the file. Repeat, Save the file again.
A copy of the original file will be appended to the original.
I'll update to your amendment and see if this still occurs here.

**Comment by Bobbicat** [comment]
After running update, the problem is no longer appearing here.
Thanks Jim
