### ISSUE TITLE
KDE dual opening application WWW

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#12]
If I open WWW from the /applications/utilities tab in the startup menu two WWW icons appear on the toolbar at the bottom of the screen for three or four seconds before one of them disappears.
It looks like two versions of the program have opened up at first.
a minor cosmetic issue I think.

**Comment by Bobbicat** [comment]
This does not happen when opening from console.

**Comment by jimbob88** [comment]
May i ask your Desktop Environment (this issue does not occur on Ubuntu 18.04 Gnome)

**Comment by Bobbicat** [comment]
I have Kubuntu installed it is the KDE desktop. I am on 18.10.

**Comment by jimbob88** [comment]
I am currently downloading Kubuntu 18.10 into a Virtual Machine, I will carry out my testing on this install ( if a fix is achieved an update will be pushed )

**Comment by jimbob88** [comment]
I have just set up a Kubuntu 18.10 install and have noticed massive text sizing issues as well as colour abnormalities, are you having the same issues (could you send a screenshot if so?)

I see the Kubuntu menu section open twice, I do not understand why this would happen though...
KDE seems to have produced many a issue for WWW

**Comment by Bobbicat** [comment]
I have had video card issues in the past. I have an nvidia card which performs much better with the recommended driver from the repos.
`sudo ubuntu-drivers devices`
might well give you a list of any recommended drivers.
I see no issues with graphics but I'll post screen a shots of WWW and the HTML print screen and you can judge.

**Comment by jimbob88** [comment]
In my KDE install there seems to be bad colours in the background ('#f0f0f2' not '#d9d9d9')

**Comment by Bobbicat** [comment]
This what I see, not much colour here on the application or the html file. But my pc does handle graphics, fonts, colour etc quite nicely. I have a coloured wallpaper on my screen, no problem, though.
It does sound like a driver or configuration issue on yours. My system will not run properly without proprietary video drivers. When I install they are one of the first things to get set up. I've been using this O.S. for years. It has been very stable and reliable. [hope I'm not tempting fate here.]

![Screenshot_20190329_181638](https://user-images.githubusercontent.com/48699320/55255142-c73cf400-5251-11e9-8f17-4ac290836527.jpg)

![Screenshot_20190329_182151](https://user-images.githubusercontent.com/48699320/55255172-d8860080-5251-11e9-826a-d6e7895f0df0.jpg)

**Comment by jimbob88** [comment]
The look of the first screenshot doesn't seem correct to me, on Ubuntu 18.04 - this is the colours given:
![Screenshot from 2019-03-29 18-57-43](https://user-images.githubusercontent.com/9913366/55256268-914d3f00-5254-11e9-9e13-775dbaf0ef60.png)

**Comment by Bobbicat** [comment]
> In my KDE install there seems to be bad colours in the background ('#f0f0f2' not '#d9d9d9')

I think what you have is not an error. 
Ignore what I said about drivers.
I think what you have is part of a specific 'theme', the default I would imagine.

Find through the startup button: Computer/System Settings/Appearance/Workspace Theme/Desktop theme and you will find a number of presets which will change the entire look of your Desktop.
KDE does mob you out with a great array of customisable options, having said that defaults should work okay, even if they are not to your taste.

You can play with settings in Kubuntu, it is much freer than Ubuntu and you can always press a button and set things back to defaults if you wish.

**Comment by Bobbicat** [comment]
Sorry, I' waffling a bit here.
I have a meal waiting for me so I must go.
but check this out in system settings, it might give you what you are looking for.
Computer/System Settings/Appearance/Application Style/GNOME Application Style

Sorry I had to dash or dinner will be in the dog

**Comment by Bobbicat** [comment]
Applications should run regardless of what theme or application style is chosen. It is possible to customise the fonts, colours, borders and much more, the application will work no matter how it looks or which options are chosen. 
Perhaps this issue should be marked as unsolved, it isn't such a big issue after all.

**Comment by jimbob88** [comment]
I have been working on a new update, and it seems to prevent odd positioning of text/colours (specifically on my system) I will push it tomorrow (GMT).

Thank you very much for your guidance, I am surprised at KDE ( I used to use it back in the day 14.04 ) but moved to XUbuntu when I had more heavy workloads... I have GNOME now after moving to so called "Normal Ubuntu" ( I had never enjoyed unity ), going back to KDE feels like an old friend. 

It feels like other DEs do not have this ability to customize, my new update moves to a global "#d9d9d9" so I can add a system in which you can change the background colour/change the buttons and labels. So all systems will look similar ( also required to provide some look  fixes under Windows ).


The main issue regarding the KDE loading seems rather odd to me. I believe what happens is it makes one for the bash script that  executes WWW and then WWW opens leaving two launchers. I will need to look into fixing this.

Hope your dinner was nice,
Jim

**Comment by Bobbicat** [comment]
I think I've found something that might be connected to it in Kubuntu. I think it is connected to the hourglass, spinning disk, wobbly icon etc you sometimes get when loading an application. I think I found the button that ebables/disables it. I'll report back in a minute.

**Comment by Bobbicat** [comment]
Yes there is a setting in Kubunttu to turn it off.
I have a WWW button on the start menu, under Applications and another on my Desktop.
Each has a button to turn off the 'feature'.
The button must be turned off for each example.

Right click on the icon/button and open Properties.
Click on the 'Application' tab.
Press the 'Advanced Options' button.
Untick 'Enable launch feedback' 
Close the 'Properties' window.
That extra icon will not appear.
This action is not system wide it only applies to the particular link to which it is applied.

I got to this by an internet search for 'Enable launch feedback'. 
A bit obscure but like much in Linux open to anyone with persistant curiosity.

**Comment by Bobbicat** [comment]
Oh and dinner was nice - if a little strange. We need to go shopping so we had what was to hand.
Sausage and macaroni cheese :)

I think many producers of applications discover pretty soon that there is the msoft way, that pretty much means that you end up with something that can only run on windows. Graham wrote somewhere that beer engine was originally written for Linux. He ported it across to Windows then very soon found that he ended up with a microsift only application and there wasn't a way to go back. I think at that point he let the thing drift - a great shame to be sure.

**Comment by jimbob88** [comment]
Good to hear you were able to both have a nice dinner and find a fix for the issue, I guess the question is if it is possible to implement this setting from the offset ( so other users do not encounter this issue ), some config file must be changed somewhere to remember the fact you disabled launch feedback. Perhaps the `.desktop` file has been changed by doing this?

**Comment by Bobbicat** [comment]
No I tested it on my machine, the change is specific to the button to which it is applied.
If a new link was made then the user would have to apply the change to that link.
If you have two buttons and one has not been 'adjusted' then that button will produce the momentary extra icon, but the other wouldn't.
I'll check the other buttons on my pc and see if that state is generally how things are.

It seems having that button [enable launch feedback] enabled is pretty much the default across the system.
So if the user at a later date created a new button that would have to be dealt with as a further separate  
occurence.

**Comment by Bobbicat** [comment]
It isn't in any sense a game changer and won't affect the application WWW in any way direct or otherwise,
plus it appears to be a KDE specific thing. 
I think my issue can be safely ignored.

**Comment by jimbob88** [comment]
Closing this issue due to a fix being available (yet it may need to be fixed later on down the road)
