### ISSUE TITLE
files in  ~/.config/Wheelers-Wort-Works

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#14]
this isn't an issue, more a 'frequently' asked question:-

I can see it is possible to open the files in the Wheelers-Wort-Works config folder in a text editor.

Beyond simply viewing these files, is it safe to edit them, alter the contents, via a text editor?
In addition, Is it safe to copy, paste, move, delete the .config/recipe files in a file browser?

Generally, by 'safe' I mean will these files still maintain their integrity within the program after they have been 'messed with'.

**Comment by jimbob88** [comment]
Answered [here](https://github.com/jimbob88/wheelers-wort-works/wiki/Frequently-Asked-Questions)
