### ISSUE TITLE
the print to HTML option

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#16]
On my setup, in the File drop-down menu, I see two options for Print.
One is labelled 'Simple HTML' and the other is 'Complex HTML'.
Whichever of these buttons I press the outcome is the same.
A nicely formatted table of ingredients and properties is shown.
It is identical no matter which button is pressed.
Is there something I am missing?

**Comment by jimbob88** [comment]
I should probably write about this in the Wiki, the complex option's tables are malleable. You can press the headers and reorder them (so you can sort by ratio, percentage, IBU, Name)
It is a `complex` option due to the requirement of an internet connection when opening it.

**Comment by Bobbicat** [comment]
> I should probably write about this in the Wiki

You can't get to everything at once. I think there might be other things in WWW that aren't immediately obvious. I'm not a programmer but I would say that a good application is one where you don't need to have studied the manual in order to get it to work properly, this is from a users point of view of course.

I hope you don't take this the wrong way, it is intended to be constructive criticism. I've only ever done rudimentary programming and I think what you are doing here is superb.

> It is a complex option due to the requirement of an internet connection when opening it.

Does this not indicate that a method to print other than using HTML might be worth looking into? Of course this would deviate from Graham's setup, so I don't know...

**Comment by jimbob88** [comment]
No no I understand fully, I feel I need some kind of pointer which tells users what the HTML file does and the differences (it really isn't obvious the difference between complex and simple to be honest). Perhaps I need some way of telling the user about that ability in a different way... Not too sure how though.

**Comment by Bobbicat** [comment]
> Not too sure how though.

This is where you lose me. I'm no programmer, as I have said before, so strategies for dealing with this sort of thing are outside of my skill set. Perhaps look at how it is dealt with in other applications by other programmers? I'm probably not being very helpful here, sorry.

**Comment by jimbob88** [comment]
@Bobbicat perhaps it would be an idea to have an alternative print/export option. I don't know where it would go though.

The only reason complex has a requirement of internet is the use of a downloadable file I don't want to have to grab the copyright for - it is easier to link the source to a website. 

The simple HTML is offline though

**Comment by Bobbicat** [comment]
I'm only guessing, but could there be an open source alternative?

**Comment by jimbob88** [comment]
@Bobbicat many others have built in opening of their printed files. For example, the ability to open let's say a table file or the ability to open some form of EXCEL-esque document...

An important thing I feel to keep, is the lack of requirement for external packages. Beer engine relies on pure built-in aspects of Python - meaning it is easier to set up...

**Comment by jimbob88** [comment]
@Bobbicat I'll do some digging for an open source one (perhaps one packageable withing my program) one slight issue with moving to an alternative is I have already written the way they work... I could always include that file just perhaps with a copyright notice above? The worst thing I could do is get WWW taken out by copyright holders

**Comment by jimbob88** [comment]
I have just checked - turns out it is licensed under the  MIT - the other issue is size. You can check it out here:
https://www.kryogenix.org/code/browser/sorttable/sorttable.js
