### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#20]
**Is your feature request related to a problem? Please describe.**
If I use the editors [hop, grist etc] and I alter something in error, there appears to be no way to return to the original default values. The only way I know is to delete all WWW config files and purge then do a complete re-install. Maybe I'm wrong but I don't know how to sort this satisfactorily.

**Describe the solution you'd like**
I would like to see it easily possible to return edited config files to default status, but with the option to also save the altered files, or a copy at least.
It would be great if all WWW config files were 'read only' from the point of view of the user. This would keep their integrity. Editing would only happen to read/write copies of the originals, perhaps kept seperate with users save files.

Unfortunately I am not a progammer, so what is easy to do and what is virtually impossble is not within my understanding. If you need more info please ask. I am very pleased to contribute and I hope in some way my comments and suggestions are useful. Perhaps introducing 'permissions' over complicates things, I don't know.

**Describe alternatives you've considered**

**Additional context**

**Comment by jimbob88** [comment]
## How to save
As always suggestions from the user for UI design will be more than welcome.
Perhaps the way to fix this Issue would be to have a save system as follows, perhaps one or multiple of these options would be a good rendition: 
- Under the default tab you can open your current config files
- Having a `Save As` button on the respective editors.
- In the respective tab i.e. Grist, Hop, Yeast Editor the user has an open button to be able to open config files
***
## Naming Scheme

The files will retain the original naming scheme in the following way (wildcard being "*"):
- `hop_data.txt` will now be saved as `*hop_data*.txt`
- `grain_data.txt` will now be saved as `*grain_data*.txt`
- `yeast_data.txt` will now be saved as `*yeast_data*.txt`
- `water_chem_data.txt` will no be saved as `*water_chem_data*.txt`
The original files will remain (i.e. `hop_data.txt`, `grain_data.txt`); however, the main config files would be those selected by the user under the defaults tab.
***

I welcome ideas openly, as I understand it is the user who should have a choise over the interface not the designer.

**Comment by jimbob88** [comment]
**NOTE:** It is possible to just delete the config files, on launch WWW checks if they exist, if they do not it creates them with default values

**Comment by Bobbicat** [comment]
> **NOTE:** It is possible to just delete the config files, on launch WWW checks if they exist, if they do not it creates them with default values

I wasn't aware of this... then really I have no issue, unless it is to explain somewhere in the manual that config files can be refreshed in this way... and perhaps warn that previous changes will be lost.

**Comment by jimbob88** [comment]
I'll add to the wiki at some point
