### ISSUE TITLE
a few example recipes provided as part of programme download.

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#21]
**Is your feature request related to a problem? Please describe.**
This is suggested as an enhancement. Examples to demonstrate the use of the program WWW.

**Describe the solution you'd like**
A simple sample recipe, saved in a recipe folder [under Samples?]
Showing how a simple example beer, a SMaSH, for example, would be set up for a one gallon brew, with 45 minutes mash and boil.. named SampleSmash.berf
A saved example, like the demo shown in set up instructions, Banks Mild, maybe, but what is copyright situation? Maybe a 'cloned' beer needs to be used/invented so no demands to take down copyright material occur. This time for a 19L brew, for 60 mins. named SampleClone.berf

Any other demo files that seem approprate. named SampleSwap.berfx
A dark ale/a light ale for example.

**Comment by jimbob88** [comment]
Perhaps having these Examples/Samples would be a good idea, I'll look into some brews I can use for this design - perhaps I could make a post about them on the Wiki (instead of incorporating them into the deb file) as it will gives users access to them. 

Perhaps also adding a button under the help menu with a link of where to get the files?

**Comment by jimbob88** [comment]
https://filebin.net/jxe1uc3rbwsrkaee 

Concept simple brew/complex brew ^^

**Comment by Bobbicat** [comment]
Perhaps these should be .berfx files rather than .berf in order to maintain compatibility when sharing across versions and machines?
I'm sure such a database could be very popular, remembering however that Graham was aiming at keeping complications and additions to a minimum.
The whole thing is beginning to look very sophisticated, I have reservations. It mustn't end up overcomplicated in my opinion.
...but overall looking very impressive.

**Comment by jimbob88** [comment]
I feel the core issue is not overcomplicating this piece of software. The thing that I always loved about the original Beer Engine was its simplicity and lack of dificulty for a new user, Graham was able to make an easily understood program that worked explicitly well. 

I feel - if there are no issues with the current version - to branch it off into a branch labelled `Stable` and work on a community driven - feature packed edition in the master branch
