### ISSUE TITLE
wiki page needs updating

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#23]
**Describe the bug**

first issue
Text display on wiki page 'Wheeler's Wort Works Starting Guide'
The recipe Banks Hansons etc could do with tidying up its all a bit scattered no proper columns.
I can screenshot if you need to see it the way it looks here.

second issue
Graphics on the wiki page 'Wheeler's Wort Works Starting Guide'
need to be updated to show changes in the appearance of the application since recent updates
**To Reproduce**
view graphics on wiki page  --> view most recent opened version of WWW
Notes Area tab is now visible. 

third issue
lower down wiki page near bottom
Also in print to html, an updated view needs to replace outdated one.
[to show 'Notes' section]

**Desktop (please complete the following information):**
 - OS: Ubuntu based 18.10 [soon to be 19.04]

Non-urgent

**Comment by jimbob88** [comment]
The Notes Area only appears if notes exists (will close for now) may ammend a guide including the Notes Area soon. Perhaps that should be focused on a complex guide as it isn't necessary
