### ISSUE TITLE
After latest update --> WWW-2.4.4_all.deb

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#24]
**Describe the bug**

after update:

`$ sudo wheelers-wort-works --coreupdate save

Updating beer_engine.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine.py
Updating beer_engine2.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine2.py
Updating brew_data.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/brew_data.py
Updating main.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/main.py
Updating update.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/update.py`

on opening WWW via console:

`$ wheelers-wort-works

Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works/main.py", line 85, in <module>
    beer_engine.main()
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 4222, in main
    gui = beer_engine_mainwin(root)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 172, in __init__
    self.master.tk.call('wm', 'iconphoto', self.master._w, tk.PhotoImage(file=resource_path('logo.png')))
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/[XXXXXXXX]/logo.png": no such file or directory`

Later I succeeded updating [see next comment]

**Desktop (please complete the following information):**
 - OS: Linux 18.10
 - Version [WWW 2.4.4]

**Comment by Bobbicat** [comment]
I tried to run `sudo wheelers-wort-works --coreupdate save` over www-2.4.3 and started to get errors and application crash.

I then downloaded wheelers-wort-works-2.4.4_all.deb and installed using qapt [a .deb installer]
seemed to go okay
www-2.4.4 is running okay now as far as I see.



**Desktop (please complete the following information):**
 - OS: Linux 18.10
 - Version [WWW 2.4.4]

**Comment by Bobbicat** [comment]
However on a closer look Inow get this error on using:  sudo wheelers-wort-works --coreupdate save
this didn't happen before

`:~$ sudo wheelers-wort-works --coreupdate save

usage: main.py [-h] [-f FILE] [-u] [-U] [-l] [-d]
main.py: error: unrecognized arguments: save
`

If I omit the 'save' and do: sudo wheelers-wort-works --coreupdate
then things seem to work okay
On the releases page in Wheelers-Wort-Works Tertiary Stable the text says : 
If .deb, On install you must run the command sudo wheelers-wort-works --coreupdate save
which didn't work correctly for me, though I think it has in the past

I don't really know what went wrong there but everything seems okay now.

**Comment by jimbob88** [comment]
Okay, so I should've updated this in the releases area but there is a whole new system now:
Where 2.4.3 now doesn't work anymore (requires the running of `--deb` at the end of the launch command. The new command system is as follows:
```
usage: main.py [-h] [-f FILE] [-u] [-U] [-l] [-d]

Arguments

optional arguments:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  The file to open `--file file_name.berf[x]` (default:
                        None)
  -u, --update          Using the current `update.py`, download the latest
                        GitHub files (default: False)
  -U, --coreupdate      Pull `update.py` from GitHub, then download the latest
                        GitHub files (default: False)
  -l, --local           Use the local mode (default: False)
  -d, --deb             Use the debian mode (only use on a Debian/Ubuntu
                        system) (default: False)

```
If you install v2.4.4 it seems to work perfectly fine with no issues.

`--coreupdate save` is now deprecated and has been converted into `--coreupdate` alone

**Comment by Bobbicat** [comment]
Is it possible, at some stage, maybe under the 'Help' tab to indiate if any update is available?

**Comment by jimbob88** [comment]
Yeah I can start work on that, the issue is that there are two ways I can work it out. (Writing this out merely ad a note to self)

# First Way
Under the help section have a button that says `Check for Update` and it goes through and compares all the local files against the GitHub files. I.E. virtually downloading to the tmp folder the files and checking if they are exact replicas of each other.

# Second Way
Save the current commit (I.e. 9fgh12) code to the `defaults.txt` and on launch if an internet connection is available and these codes are different notify of an update.

**Comment by Bobbicat** [comment]
I think the second way sounds to me, as a non-programmer, a more straight forward approach requiring less 'processing'. If you intend to make this app available for mobile devices [which sounds like a good idea to me] the less of this processing the better I would imagine.
