### ISSUE TITLE
Efficiency display in 'Calculation' pane on Engine Room tab

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#26]
**Describe the bug**

**To Reproduce**
in defaults editor: 
enter 54% efficiency or below --> no problem
enter 59% efficiency or above --> no problem
enter efficiency 55,56,57,or 58% --> check out calculation pane in engine room
--> efficiency will be displayed with a large number of decimal places

**Expected behavior**
Enter any 'efficiency' outside the above range  for example 50%, 60% or 70%, will produce normal behaviour

**Comment by jimbob88** [comment]
@Bobbicat I have a fix ready to be shipped so will close this issue for now (it'll be released once I have created a commit updating system)
