### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#29]
the last update seems to run okay.
on starting WWW the Update pop-up appears saying that there is a new update available.
On running, wheelers-wort-works --coreupdate, this update message continues to be displayed at start up.
The last update does appear to have been applied.

**Comment by jimbob88** [comment]
This is issue is fixed in commit `dd7497dac5431219fe13fa1fcc02dcf8549d5d74` please try updating again
