### ISSUE TITLE
Error found when using 'Experimental Attenuation'

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#3]
I have found errors as stated in the title of this issue. 
I'm investigating how and when they occur and will post again soon when I have some data.

**Comment by Bobbicat** [comment]
I started wheelers-wort-works via the console.
I saved 'No Name' - and then made up a 'Trial Run' file. On checking it turned out both these files were owned by root. No errors had shown up in the console.
I'll delete them and walk through it again to try to find where root is coming into things.

**Comment by Bobbicat** [comment]
I had run sudo wheelers-wort-works --update in the console, so in effect I was running W-W-W from root.
I'll go through it again and check. I think a reminder or warning possibly needs to be added to restart W-W-W after an update. 
I'll post what I discover.

**Comment by Bobbicat** [comment]
I have posted the above as another issue.
I will continue to investigate the Experimental Attenuation tab.

**Comment by Bobbicat** [comment]
When constructing a recipe everything goes well until I use 'Experimental Attenuation'.
I can enter a yeast successfully but if I add 'Irish Moss' errors occur and I cannot perform a successful save.

**Comment by jimbob88** [comment]
Is it possible for you to paste the given error to help pinpoint the area of the error so it can be fixed rapidly
- jim

**Comment by Bobbicat** [comment]
I'm not sure if this covers it all:-

I set up 'No Name'
Grain - Maris Otter 1kg
Hop   - Admiral 4g
Water Chemistry - Irish Moss 

this all saved ok

on attempting to print to browser the following appeared in the console::

```$ wheelers-wort-works

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 1346, in create_html
    temp_hop = list(sorted([x for x in temp_hop if x is not None], key=lambda k: k['Values']['Time']))
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by jimbob88** [comment]
Okay thank you very much, I'll get back later today with a fix hopefully

**Comment by Bobbicat** [comment]
I'll keep an eye on this thread, thanks for your hard work.
