### ISSUE TITLE
Another Notes tab request

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#31]
There seems to be a limitation on the font in the Notes area.
I pasted in a symbol for degree ° and something happens to the text in the pane after a save or restart, the same thing happens after entering  for example:

½ tsp gelatine      [2g]
⅔ cup water at 65°C [160ml]

try the above two lines pasted into the notes, save and close, then restart, to see what I mean.
there are possibly other  issues like this.

**Comment by jimbob88** [comment]
Looks like the encoding for default `.berf` files (ISO-8859-1), doesn't support the character ⅔; however, berfx does. I would recommend saving as `.berfx` when working with complex text, due to the use of UNICODE over Latin encoding systems.

**Comment by Bobbicat** [comment]
Thanks Jim, that works good for me.
In the Wiki you could add a Hints and Tips section.
Using .berfx files to deal with complex files, could be one such tip.
