### ISSUE TITLE
Issue with www 2.4.6

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#34]
I am between purging, installing, then purging and reinstalling with and without QApt, in both kubuntu 1810 and kubuntu 1904.
using www 2.4.6 each appear to fully install correctly, whichever OS version and/or by whichever installation method.

**however**

in a newly installed, newly opened www, if I chose 'File/Open' then click 'Cancel' the following comes up:

```
$ wheelers-wort-works
Already the Latest Edition
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 216, in <lambda>
    command=lambda: self.open_file(filedialog.askopenfilename(initialdir = os.path.expanduser('~/.config/Wheelers-Wort-Works/recipes/' if __mode__ == 'deb' else '.'), title = "Select file", filetypes = (("BERF","*.berf *.berfx"), ("all files","*.*")))),
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 1628, in open_file
    if file.lower()[-5:] == '.berf' or file.split('/')[-1] in examples:
AttributeError: 'tuple' object has no attribute 'lower'
```

I'm sorry that I seem to be fault finding so much. I want you to know that I think you are doing great work here and WWW is getting better all the time, all down to you.

**Comment by jimbob88** [comment]
I am merely happy somebody is able to user my software, and that I can find fixes to bugs that do crop up - as I've said previously - the worst thing that could've happened would be issues to stay hidden until they all build up into one big failing application. I thank you for your dedication and patience with this project
