### ISSUE TITLE
feedback on jim's beer kit forum

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#36]
This is more of a comment than an issue

You are getting feedback on JBK Forums.
A number of people seem to be trying out Wheelers Wort Works.
You are creating an interest.

https://www.jimsbeerkit.co.uk/forum/viewtopic.php?f=77&t=17405&start=210

I hope you are comfortable with my making your application more public, in my opinion it does deserve attention and will likely be useful to many home brewrs.

**Comment by jimbob88** [comment]
Yeah I am more than comfortable, I'd rather more people were to know about the software than not, thank you so much for posting and mentioning its existence. Good to hear people are using my software! 

Thank you so much 
- Jim

P.S:
As seen as the current edition of wheelers-wort-works seems mostly stable (except for a few issues surrounding MacOS/Windows look and feel) I have been working on developing for the web, here is a sneak peek of the extremely beta software:
![Screenshot from 2019-05-02 16-40-28](https://user-images.githubusercontent.com/9913366/57087895-064ee100-6cf9-11e9-908b-38ef28ed00c0.png)

As you can most likely see it is extremely beta and still needs LOTS of development before a usable edition can be released but this is the basic concept (it was originally built using a translation layer between TCL/TK and REMI for those who are interested)
