### ISSUE TITLE
Working with Editor tabs

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#37]
I don't think this is a new issue

**To Reproduce**

Open Wheelers-Wort-Works
Open an editor - i've only tested Hops but I think it applies to the others too.
create a new hop by pressing 'New' in the editor
'New Hop 0'  will be created
click 'Modify' button and edit 'New Hop 0' [re-name it 'my hop' for example]
click 'Done' button
Then press 'Save to Database' button
a new hop with your new name 'my hop' appears on the list, 
'New Hop 0'  is also still on the list
Should 'New Hop 0' not have been overwritten by 'my hop' and no longer be seen?

**Comment by Bobbicat** [comment]
As a further related issue, I think editing the data files is a process easy to get wrong.

There is a sequence to follow that is not necessarily apparent.

After the Done button has been pressed it is also necessary to press 'Save to Database' or the data is not stored. This is not obvious.
Pressing the 'Done' button implies editing is complete which is not so until the save button is pressed.
Maybe the 'Done' button is misleading and redundant and all that is needed is a 'Save' button?

It could be I've missed something here but I'm not sure what it is.

**Comment by jimbob88** [comment]
The way the editor system works is odd I understand but required at this moment in time. Perhaps names should be changed? The function of the `Done` button is to temporarily save your current data-set so you could change a data value for only a single recipe than save as a `.berfx` - rather than having to reload and change the database every time

**Comment by Bobbicat** [comment]
I understand what you are saying.
I think it would be a good idea to make it plain that if changes are made to any of the editor files then it is a good idea to save any recipes affected as .berfx files for the time being.
There are workarounds but I think a new user would be very discouraged to find their recipes were no longer operational, with no obvious cause.

**Comment by jimbob88** [comment]
I think that's a good idea - I'll set it as the default in the backup release

**Comment by Bobbicat** [comment]
In addition I've been going through older recipes before the notes tab was introduced, they now throw up an error related to that. I don't think that needs correcting, but...
Major changes are likely to make older saved files inaccessible so I think a general rule to always save as .berfx ought to apply for now.
Making it default as you suggest would sort that out for now.
