### ISSUE TITLE
A backup/restore file for WWW

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#38]
**Is your feature request related to a problem? Please describe.**
I have been using, installing and re-installing WWW. At some stages I have even purged all files to try to correct an error and as a result lost my recipes and edits.

It would be handy if there was a feature to backup/restore the essential parts of the .config file on an occasional basis. Perhaps it could be set up so several backups could be stored each dated so they would be easy to identify. Maybe this is over complex for a start.

Just press a button to backup Recipes folder and _data.txt files to a folder of your choosing.
Another button to restore from backup, with a warning that this will overwrite files already in place.

**Describe the solution you'd like**
Providing an easily accessible means to backup user files would be an asset. 

**Describe alternatives you've considered**
Of course it is possible to save the config file without buttons and so on, but would the average user be able to do this?

**Comment by jimbob88** [comment]
Added in community_edition

**Comment by Bobbicat** [comment]
Can I access community_edition?

**Comment by jimbob88** [comment]
Soon I am going to be making a `.deb` for community_edition but for now on the github page for WWW where it says branch master click it and you can change to community edition..
But as I said at some point I will be make a deb file or Linux executable

**Comment by Bobbicat** [comment]
Looks like I will have to wait for the .deb file.
I'm out of my depth now.

**Comment by jimbob88** [comment]
I haven't fully tested this but this is the basic idea for a command system to update to community_edition:
```sh
sudo wget https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/community_edition/update.py -P /usr/include/wheelers-wort-works/
sudo wheelers-wort-works --update
```

**Comment by jimbob88** [comment]
The Deb has now been released sorry for the wait :+1:

It now uses the command line `wheelers-wort-works-ce` CE being community edition

**Comment by Bobbicat** [comment]
I have problems with this, posted new issue.
