### ISSUE TITLE
Notes area bug

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#39]
**To Reproduce**
1. Open wheelers-wort-works in the terminal [Linux]
2. Open a recipe
3. Enter a line or two of text in the 'Notes Area'
4. Save the recipe
5. See text from Notes Area appear in terminal.
6. Close wheelers-wort-works.
7. See text from Notes Area appear for a second time in terminal.

**Desktop (please complete the following information):**
 - OS: Linux 
 - Version: disco dingo 1904

**Comment by jimbob88** [comment]
The reason for this is the auto save-on-close feature so the notes+your recipe are saved and then when you close the file is saved again - hence the notes being printed

**Comment by Bobbicat** [comment]
Should the contents of Notes Area be printed into the terminal area?
That wasn't happening until recently.
this is the display I now get in the terminal:

> $ wheelers-wort-works
Already the Latest Edition
"I wrote this in the Notes Area\nThis is displayed on 'save' in the console\n"
"I wrote this in the Notes Area\nThis is displayed on 'save' in the console\n"

 The above is the feedback in the terminal when I open, save and then close wheelers-wort-works

**Comment by jimbob88** [comment]
It is simply just a debug bit of code I have currently in place, whenever I am implementing a feature I print every step of the process so I know where it truly failed if it inevitably does. 

I will soon remove it and release a so called `stable-edition` which has the current feature set, with no special addons.

**Comment by Bobbicat** [comment]
I'm very ignorant about programming - sorry to fuss so much

**Comment by jimbob88** [comment]
No issue at all, I'm just happy you're sticking with it
