### ISSUE TITLE
Error after running 'sudo wheelers-wort-works --update'

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#4]
I found that some of my '.berf' files were owned by root.

If WWW is run as sudo then files saved are owned by root.
This is likely to occur after running 'sudo wheelers-wort-works --update' as suggested on the Releases page. 
To avoid this WWW needs to be restarted after updating, so that it and its saved files are user owned.

**Comment by Bobbicat** [comment]
Although .berf files become owned by root this does not occur to .html saved files.

**Comment by jimbob88** [comment]
Error noted, was encountered earlier today, when I return home I can begin working on a quick fix
