### ISSUE TITLE
new install of community edition

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#43]
**Describe the bug**
I used QApt to install from file wheelers-wort-works-ce_0.1_all.deb
All dependencies were met.

on attempting to run:

`$wheelers-wort-works-ce
Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works-ce/main.py", line 114, in <module>
    beer_engine.main(update_available=update_available)
  File "/usr/include/wheelers-wort-works-ce/beer_engine.py", line 4422, in main
    gui = beer_engine_mainwin(root)
  File "/usr/include/wheelers-wort-works-ce/beer_engine.py", line 41, in __init__
    with open(resource_path('defaults.txt'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/XXXXX/.config/Wheelers-Wort-Works-ce/defaults.txt'`

the community edition config file has not been created, not even after an update or a coreupdate
but community edition is reporting it is latest edition, appears to load okay but is using config for www standard edition.

I'll keep an eye on things and test any updates.

**Comment by jimbob88** [comment]
This seems to be an Issue with Qapt installer. For this moment in time could you use the command:
```bash
sudo apt install ./wheelers-wort-works-ce_0.1_all.deb
```
or use GDEBI installer, it installs in a way that seems to result in few to no issues for me with WWW

**Comment by Bobbicat** [comment]
$ sudo apt install ./wheelers-wort-works-ce_0.1_all.deb
[sudo] password for XXXXX: 
Reading package lists... Done
E: Unsupported file ./wheelers-wort-works-ce_0.1_all.deb given on commandline

**Comment by jimbob88** [comment]
That seems odd, maybe I should've mentioned you need to be in the folder containing the DEB file

**Comment by Bobbicat** [comment]
My mistake, sorry. I'll explain in a minute.

**Comment by Bobbicat** [comment]
I wasn't in the correct folder, as you thought, so I repeated that line [sudo apt install ./wheelers-wort-works-ce_0.1_all.deb] in the correct place, with this result:

`$ sudo apt install ./wheelers-wort-works-ce_0.1_all.deb
[sudo] password for XXXXX: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wheelers-wort-works-ce' instead of './wheelers-wort-works-ce_0.1_all.deb'
wheelers-wort-works-ce is already the newest version (0.1).
`

A Wheelers-Wort-Works-ce configuration file is not being created and the community edition is accessing the normal WWW config file. Is this right?

**Comment by Bobbicat** [comment]
Is the problem because I have not removed the WWW standard edition? I have both 'installed' on my PC

**Comment by Bobbicat** [comment]
I have one or two things to do - I'll be back in an hour.

**Comment by jimbob88** [comment]
Perhaps you need to remove the current version, sorry about the issues

**Comment by Bobbicat** [comment]
Life would be so boring if there were no challenges Jim. I'm quite happy to do what I can here.

I'll purge all community edition files and do a more careful install. I'll be eating soon, but I'll get back with results as soon as I am able.

**Comment by Bobbicat** [comment]
I purged all community edition files. I'm still not getting a working application after running install.
After install should I be running --update, --coreupdate or anything else?

**Comment by Bobbicat** [comment]
I'll purge all wheelers-wort-works and wheelers-wort-works-ce and see where that takes me.

**Comment by Bobbicat** [comment]
successfully purged all wheeler related files
re-downloaded wheelers-wort-works-ce_0.1_all.deb
installed by:
sudo apt install ./wheelers-wort-works-ce_0.1_all.deb

`$ sudo apt install ./wheelers-wort-works-ce_0.1_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wheelers-wort-works-ce' instead of './wheelers-wort-works-ce_0.1_all.deb'
The following NEW packages will be installed
  wheelers-wort-works-ce
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/300 kB of archives.
After this operation, 848 kB of additional disk space will be used.
Get:1 /home/bob/wheelers-wort-works-ce_0.1_all.deb wheelers-wort-works-ce all 0.1 [300 kB]
Selecting previously unselected package wheelers-wort-works-ce.
(Reading database ... 205487 files and directories currently installed.)
Preparing to unpack .../wheelers-wort-works-ce_0.1_all.deb ...
Unpacking wheelers-wort-works-ce (0.1) ...
Setting up wheelers-wort-works-ce (0.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...`

a community edition config file has been created
on running wheelers-wort-works-ce:

> pop-up:
an update has become available, it is recommended you run the command: sudo wheelers-wort-works --coreupdate

Should the command in the popup read:
sudo wheelers-wort-works --coreupdate
or
sudo wheelers-wort-works-ce --coreupdate
??

**Comment by jimbob88** [comment]
Yeah it should say that thanks for the report! I'll change wheelers-wort-works to community edition!

Thanks again!

I have just realised I think the update system itself needs an update as the notification may still be based off the master branch! 

I'll fix this later today!

**Comment by Bobbicat** [comment]
Yes I only just this minute got this:

```
$ sudo wheelers-wort-works --coreupdate
sudo: wheelers-wort-works: command not found
```

```
$ sudo wheelers-wort-works-ce --coreupdate
Updating beer_engine.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine.py
Updating beer_engine2.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine2.py
Updating brew_data.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/brew_data.py
Updating main.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/main.py
Updating update.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/update.py
```

**Comment by jimbob88** [comment]
Sorry about that, as I said I'll release a fix later today

**Comment by Bobbicat** [comment]
This was the result:

```
$ wheelers-wort-works-ce
Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works-ce/main.py", line 114, in <module>
    beer_engine.main(update_available=update_available)
  File "/usr/include/wheelers-wort-works-ce/beer_engine.py", line 4248, in main
    gui = beer_engine_mainwin(root)
  File "/usr/include/wheelers-wort-works-ce/beer_engine.py", line 40, in __init__
    with open(resource_path('defaults.txt'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bob/.config/Wheelers-Wort-Works/defaults.txt'
```

will i need to purge and re-install?

**Comment by jimbob88** [comment]
That doesn't seem right as well, for some reason it seems to be pulling from wheeler's Master branch, I was pretty sure I changed that value!

Sorry about the concurrent issues

**Comment by Bobbicat** [comment]
no probs - I'm sure you'll get it sorted

**Comment by jimbob88** [comment]
Yeah sorry about this you need to reinstall and not update, the update. py seems to've not been not changed in the latest edition

**Comment by jimbob88** [comment]
The deb file needs an update

**Comment by Bobbicat** [comment]
Okay, I'll wait until you can fix it.

**Comment by Bobbicat** [comment]
I've purged the ce I'll wait for developments. Thanks for your work on this.

**Comment by jimbob88** [comment]
The `.deb` file has now been pushed, with the same version number, so a purge has to be completed first!

Sorry about the issues!

**Comment by Bobbicat** [comment]
I installed successfully using:
`sudo apt install ./wheelers-wort-works-ce_0.1_all.deb` 
and updated with:
`sudo wheelers-wort-works-ce --coreupdate`

That all went fine and looks okay so far,

...and no worries about issues, it is great to see your work progressing so well.

**Comment by Bobbicat** [comment]
The message in the **update popup** needs changing from:

> An update has become available, it is recommended you run the command: sudo **wheelers-wort-works** --coreupdate

to:

> An update has become available, it is recommended you run the command: **sudo wheelers-wort-works-ce** --coreupdate

**Comment by jimbob88** [comment]
Closed as I assume there is no more current issues :) - I hope anyway
