### ISSUE TITLE
Text in update Popup

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#44]
**Describe the bug**

When a new version of wheelers-wort-works-ce is available a popup appears on starting the community edition application.

The incorrect text in the pop up states:

> An update has become available, it is recommended you run the command: sudo **wheelers-wort-works** --coreupdate

this should be edited to read [for community edition]:

> An update has become available, it is recommended you run the command: **sudo wheelers-wort-works-ce** --coreupdate

**Desktop (please complete the following information):**
 - OS:  Linux
 - Version [deb community edition]

**Comment by jimbob88** [comment]
Sorry about that, fixed in the latest release :)

**Comment by Bobbicat** [comment]
The latest release is not producing an update popup
