### ISSUE TITLE
update popup not appearing

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#45]
**Describe the bug**
The latest release is not producing an update pop-up

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [c.e deb file]

**Comment by jimbob88** [comment]
Seems to work for me, on deletion of the `commit.txt` a pop-up appears for me and I can update.

Not sure what the issue is here, maybe it was just a one off?

**Comment by Bobbicat** [comment]
I ran 
`sudo wheelers-wort-works-ce --coreupdate`
then I renamed commit.txt as xcommit.txt
On restarting the 'Update Available' popup appeared and its text was correct.
I'm closing this as the popup and its text is now functioning correctly.
