### ISSUE TITLE
Interface, editors, minor problem 

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#46]
**Describe the bug**

**To Reproduce**
1. Open wheelers-wort-works-ce
2. Click on 'Hop Editor....'
3. At top of left-most panel see 'Hops:' panel label
4. Click on 'Grist Editor....'
5. At top of left-most panel, is NOT 'Grist' - Hops still showing
6. Check other 'Yeast Editor' page - this also shows 'Hops:' as label to panel.

**Comment by jimbob88** [comment]
In my install of Wheeler's Wort Works this issue doesn't seem to occur?

![Peek 2019-05-15 20-16](https://user-images.githubusercontent.com/9913366/57802608-4927a480-774e-11e9-8ac3-191c62b7995e.gif)

**Comment by jimbob88** [comment]
Oops just realised it does happen - forgot to pull a newer edition! Sorry about that I'll push a fix now.
