### ISSUE TITLE
Editing the Ingredient database

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#48]
After having tried making additions to the Hop and Grist databases and later editing those additions, I am not sure how well it all plays with berfx files.
I need to test a bit more to see exactly how this works out.

for example:
I create a new hop, say 'my New Hop' then create a recipe using 'my New Hop' and save it as a berfx  
Later I attempt to edit 'my New Hop'.
At this point I'm not sure if this is possible, or if it will negatively impact the berfx file, or vice versa, Sometimes after an attempted edit 'my New Hop' disappears from the Hops list, then after opening a berfx file it reappears.

All of the odd behaviour might be because I do not know how to use the Editor properly, I'm not sure I know how and there are no instructions. So perhaps it is user error.

At  the least a short demo/tutorial or instruction set for using the editors would be useful.

**Comment by Bobbicat** [comment]
I am re-writing my edits from scratch. I purged and deleted the original stuff. I should get a better idea of things if I start again like this. First I'm entering my Hops and my Fermentables. Next I will recreate my recipes, luckily I don't have a stack of them.

**Comment by jimbob88** [comment]
I believe the issue that was occurring was mainly due to the fact the ordering of the listbox - the listbox fix has been released to help with this issue.

To change a value on pressing the `Done` button, it gets saved to your temporary database - pressing Save To Database does not click the `Done` button - it does this afterwards

**Comment by jimbob88** [comment]
Is this here fixed (shall I close it) or are there still changes wanted? :)

**Comment by Bobbicat** [comment]
I will check this out - but a recent update has created a problem, so I will hold back on this until the other is sorted.

**Comment by Bobbicat** [comment]
I'm still intending to re-investigate this issue. Sorry for the delay.

**Comment by Bobbicat** [comment]
I think I lost my way with this. I've tried to retrace my steps but can't find the issue now. 
I'll close this and if I come across it again I'll open a new issue with a better description.
Having said that, you probably sorted it anyway.
