### ISSUE TITLE
Colour Indicator

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#5]
An area with a colour scale and a pointer would be useful to display actual colour from effective EBC.

**Comment by jimbob88** [comment]
Just to clarify, what exactly would you like as a colour indicator. Would you want a scale like this:
![ind_scale](https://user-images.githubusercontent.com/9913366/55025034-ffe19100-4ff7-11e9-9921-d58f93aab3e9.png)

Or would you prefer a simple box that contains the current colour of your beer, or perhaps a more beer smith like approach.

**Comment by Bobbicat** [comment]
Personally I think a scale with an indicator bar gives a good indication of any changes that might be made,
darker or lighter [like brewtarget]. Of course a box uses up less of the display area.

**Comment by jimbob88** [comment]
Oh, okay. I believe the current issue is that I wish to keep to the idea of Graham Wheeler's Beer Engine, with it being simple and not becoming overly cluttered. So something like [brewtarget](http://www.brewtarget.org/) has many options and menus. I wish to keep this program as simple as possible. What I was considering doing was having a refined tab based system in which extra data can be found in other areas I.e. being able to open a tab with this extra details. I could perhaps house the colouring section there. 

May I ask your opinion on this matter, where would you personally place the colour indicator?

**Comment by Bobbicat** [comment]
I think you have something there. Keeping it uncluttered is an excellent aim. Perhaps the colour indicator should be left off for now. 
At this moment I think the fact that all the data and predictions for the brew can be found on the front page is a strength. It is easy to set up and easy to read and I do prefer it that way. I think it is great that you want to stick to Graham's original format, it has many advantages.

Setting up the hop editor is straight forward enough but I'm not sure how to work with the grist editor. Maybe it is just me but some instructions would be useful.

*addition - I've just found some information written by Graham on the JBK forum - I think it will answer some of my questions - I'm away to read it.

**Comment by Bobbicat** [comment]
I just came across this written by Graham on the JBK forum in 2010:

> One little programme that does one job very, very well, exceptionally well, rather than a programme that does several things half-heartedly, was BeerEngine. 

I think you are hitting the nail squarely on the head. This is exactly as it should be.

**Comment by Bobbicat** [comment]
I think this issue is a distraction and will close it here.
