### ISSUE TITLE
Opening a new recipe when another recipe is already open.

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#52]
**Is your feature request related to a problem? Please describe.**

If for example you have a recipe, which you have edited, open and you choose to open another recipe then your original edits will be lost. It is not necessarily obvious that a save is needed.

I feel there is a need to either automatically save the original file before it closes and the new file opens, or at least give an option or warning to save before closing and opening the next recipe.

I think that in general if the recipe or program is about to close a warning that changes will not be saved unless action is taken should be provided.

If this is unclear I'm happy to try to explain further. I apologise , not being a programmer, I don't have the concepts and language relating to issues like this.

By the way, a little positive feedback. I am finding this program useful for recipe design and testing, your efforts are very much appreciated.

**Comment by jimbob88** [comment]
Surrounding this point I have started work on it (and have nearly finished it), this dialogue that you wish to have pop-up, would you like it to appear before or after the file open dialogue.

It is no extra work either way so I don't mind which way it is implemented
