### ISSUE TITLE
after update #52

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#53]
After update #52 there is no notification/reminder as is usual to run:
 sudo wheelers-wort-works-ce --coreupdate

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [kubuntu 1904]

**Additional context**
Running wheelers-wort-works-ce

**Comment by jimbob88** [comment]
That seems rather odd. I have just updated base wheelers-wort-works with a new update dialog (hopefully this fixes some issues) and am porting it to ce now.
I am not at my main PC right now (I am running on a laptop) so cannot compile a new deb file with these bug fixes but with any luck I will have a compiled deb by the weekend

**Comment by Bobbicat** [comment]
I'll save updating until the notification appears. I can wait.
Thanks very much for your efforts.
