### ISSUE TITLE
I manually updated WWW-ce as it created no notification of any update available at startup

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#54]
the title of this item describes the error

**Comment by jimbob88** [comment]
Yes, I have discovered the source of this issue, and it is because of a change of styling on the github main page, I should be able to post an update to fix this issue shortly, sorry but there will be no notification for this event happening but future updates should arrive with a notification!

**Comment by Bobbicat** [comment]
I am still manually updating WWW-ce. I've seen no notification of updates recently, since reporting this issue.

**Comment by jimbob88** [comment]
I'll need to do some more work into looking at a fix for this. I'll get back tomorrow with the reason for the issue!

**Comment by Bobbicat** [comment]
> An update has become available, it is recommended you [quit and] run the command:
sudo wheelers-wort-works-ce --coreupdate

A couple of points - 

would it be a good idea to include the words 'quit and' so that www will be restarted after the update?
and,
is it necessary to use sudo for the update?
I seem to remember not needing to...

otherwise all looking good

**Comment by jimbob88** [comment]
Yeah I'll append the quit to the dialogue once I'm back on my workstation, good idea. With the sudo, it appears while running the Debian/Ubuntu installation of WWW, because on Ubuntu 14.04 - 19.04 you require sudo. Perhaps your permissions are different in Kubuntu but in base Ubuntu it is necessary so it is there as a just in case measure so people don't fill the issues page with "sudo" errors.

**Comment by Bobbicat** [comment]
I've checked back through my history and it seems I have been using sudo when doing a coreupdate. 
I apologize for my misleading statement.

**Comment by jimbob88** [comment]
No worries! So are you still encountering issues where the upload dialog doesn't appear? Thanks in advance, Jim

**Comment by Bobbicat** [comment]
I think it is sorted now.
I will open a new issue if I come across anything else.
