### ISSUE TITLE
www tabs anomally

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#56]
**Describe the bug**
when as tab is pressed in www a label int number appears in the console area.

**To Reproduce**
1. open www
2. Click on any tab [for example 'notes']
3. 

**Expected behavior**
no output expected on clicking a tab

**output in console on clicking tabs in reverse order**
wheelers-wort-works-ce
6 <class 'int'>
5 <class 'int'>
4 <class 'int'>
3 <class 'int'>
2 <class 'int'>
1 <class 'int'>
0 <class 'int'>

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [kubuntu1904]

**Additional context**
ask if I'm not being clear enough

**Comment by jimbob88** [comment]
This was originally a debugging section of the script, as when clicking on the different tabs a refresh command has to be run. For example, Engine Room: Recalculate and Hop/Grist/Yeast Editor: Refreshes the list of ingredients! It no longer needs to exist in the code so has been commented out now!
