### ISSUE TITLE
Using the add hop and add new [grist] buttons

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#58]
**Describe the bug**
On pressing 'add new' or 'add hop' buttons a pop-up appears with no content
this occurs while editing already saved recipes and also when trying to create a new recipe

**Comment by jimbob88** [comment]
With this issue do you think you could launch the program from the terminal and executing this again, it would be interesting to see the errors that occur and would give a better idea of the issue at hand. Also perhaps trying pressing the Left CTRL key on your keyboard when the window appears a few times - I have had this fix issues surrounding grey windows but it sounds more likely to be an issue surrounding the databases.

**Comment by jimbob88** [comment]
I found the issue, please inform me if this fixes it for you too, I forget to add a help URL!

**Comment by Bobbicat** [comment]
After running coreupdate the issue is corrected.

**Comment by Bobbicat** [comment]
I didn't run update so maybe the above is wrong

**Comment by jimbob88** [comment]
On my system, the update I released was able to fix it... So you think you could force update it again?

**Comment by Bobbicat** [comment]
Yes my apologies - I hadn't run coreupdate - your fix works fine after updating.

**Comment by jimbob88** [comment]
No issues, good to hear it is fixed!
