### ISSUE TITLE
Opening a recipe for editing

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#59]
**Describe the bug**
When 'opening' a saved recipe for editing, the dialogue does not proceed directly to the WWW.ce folder, instead it stops at the home/user file leaving the user to find their own way to :
home/user/.config/Wheelers-Wort-Works-ce/recipes

This also occurs if 'saving as'.

**Desktop (please complete the following information):**
 - OS: [kubuntu]
 - Version [1904]

**Comment by jimbob88** [comment]
This should be fixed in the latest update!

**Comment by Bobbicat** [comment]
It is fixed here, many thanks
