### ISSUE TITLE
fresh linux install of www-ce

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#60]
**Describe the bug**
after a fresh install of my OS followed by install of www-ce an error message is generated in the console.

**To Reproduce**
1. Uninstall www-ce and remove ~/.config/Wheelers-Wort-Works-ce/
2. Re-install www.ce and run www-ce --coreupdate
3. Attempt to run www-ce in console
4. See error:
`No such file or directory: '~/.config/Wheelers-Wort-Works-ce/defaults.txt'`
5. www-ce does not start

**Expected behavior**
I expect www-ce to start up wth no errors.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: focal2004  www-ce 1.1.0 

**Additional context**

It appears from the error message that on fresh installation the required file "~/.config/Wheelers-Wort-Works-ce/defaults.txt" is not created so the program will not start up.

As a workaround I manually created an empty "~/.config/Wheelers-Wort-Works-ce/" folder.
When I attempted to restart the program the folder was populated and the program started up successfully.
This folder obviously should be created at the installation stage. 
An empty folder will suffice, the installation takes care of the rest.

!!! urgent !!!
I think this bug needs urgent attention as it prevents a new user from accessing the program
If you need more info please ask - I'll be watching this issue - B

**Comment by jimbob88** [comment]
Hey there,

Thanks for bringing this to my attention, on my system I was able to get an installer that works (I am also running focal).

You can download the latest version from the [release](https://github.com/jimbob88/wheelers-wort-works/releases/tag/v0.2)

Sorry about that,

Jim

P.S.

I believe I need to rebuild the base version of wheelers-wort-works too! Thanks again!
