### ISSUE TITLE
README file for www-ce

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#61]
**Describe the bug**
Incorrect text in readme file for www-ce

**To Reproduce**
1. Go to 'community edition code'
2. Click on 'README.md'
3. Scroll down to 'Linux>Ubuntu or Debian...'
4. See error:-
> It is also recommended to run the command `sudo wheelers-wort-works --coreupdate save` so as to get the most out of Wheeler's Wort Works 

**Expected behavior**

`sudo wheelers-wort-works --coreupdate save` 

should read:

`sudo wheelers-wort-works-ce --coreupdate`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu
 - Version focal2004

**Additional context**

looking further in the readme I notice most references are for the master edition and not community edition

**Comment by jimbob88** [comment]
Hey there,

Thanks, yeah I forgot that was deprecated, I'll fix this when i get to my  PC!

Thanks again,

James

**Comment by Bobbicat** [comment]
There is still more here under expected behaviour:
you have corrected to
`sudo wheelers-wort-works --coreupdate`

this should be

`sudo wheelers-wort-works-ce --coreupdate`

note missing -->   -ce

**Comment by jimbob88** [comment]
Oh, yeah!

I think I have changed most of them on the community_edition README
