### ISSUE TITLE
Grist Editor

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#7]
In the Grist editor:
The type 0.0 is still on the type list, now at the bottom of the list.
Is this a necessary type? Please forgive my ignorance.

The default for Crystal Malt now has 0.0 as its type. 
Should this be 'Can be steeped'?
All the other entries appear to be okay.

Should I have posted this as a new issue?

**Comment by jimbob88** [comment]
This seems odd, on my system this doesn't result as an issue - can you send your `grist_data.txt` file as I do not believe I have any under this formatting. It doesn't appear to be an issue under my dataset.

Perhaps it would be useful for you to also state what `0.0` falls under in your copy of beer engine

**Comment by Bobbicat** [comment]
here's the file you asked for:
it has some experimental additions by me. I did not edit any of the default entries.

[grain_data.txt](https://github.com/jimbob88/wheelers-wort-works/files/3014064/grain_data.txt)

perhaps a re-install might correct it?

> Perhaps it would be useful for you to also state what 0.0 falls under in your copy of beer engine

How would I check this?

**Comment by jimbob88** [comment]
This seems to be an issue with your config file `Crystal Malt` should not be 0.0, it should be changed to the appropriate number, Crystal malt is normal 4.0:
```
'Crystal Malt': {'EBC': 130.0, 'Type': 4.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 4.5, 'Fermentability': 50.0},
```

**Comment by Bobbicat** [comment]
I understand what you are saying.
I have purged wheelers-wort-works and am about to do a complete fresh re-install.

**Comment by Bobbicat** [comment]
The purge and re-install seems to have cleared that up. I think the file had become corrupted, probably by my repeat alterations and tests. I think this was not a bug in the program. The grist type option '0.0' has disappeared from the grist 'type' options drop down menu too.
