### ISSUE TITLE
Opening a saved file

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#9]
I have created a couple of files on WWW. 
They appear to have functioned correctly, the results look okay and they saved without any problem. 
However on attempting to open them after a save I get:

```$ wheelers-wort-works

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 485, in <lambda>
    command=lambda: self.open_file(filedialog.askopenfilename(initialdir = os.path.expanduser('~/.config/Wheelers-Wort-Works/'), title = "Select file", filetypes = (("BERF","*.berf *.berfx"), ("all files","*.*")))))
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 1545, in open_file
    self.sixth_tab.original_additions = list(set(self.sixth_tab.original_additions, key=self.sixth_tab.original_additions.index) - set(self.sixth_tab.added_additions))
TypeError: set() does not take keyword arguments
```

**Comment by Bobbicat** [comment]
Please forgive my ignorance.
When these bugs are corrected is it sufficient to run:
`sudo wheelers-wort-works --update` ?

**Comment by jimbob88** [comment]
Yes that will work unless specifically noted, that command will help

**Comment by jimbob88** [comment]
Big changes need a new update ( I'd recommend the latest 2.4.1 deb file )

**Comment by Bobbicat** [comment]
Thanks Jim, sorry I'm inundating you with bugs.

**Comment by jimbob88** [comment]
Absolutely no issue, I'd rather have someone tell me there are issues, than having issues that build up continually over time.
